In [1]:
import pandas as pd
import numpy as np
from pathlib import Path
import simplekml

In [4]:
# --------------- Paths ------------------------
area_file= Path("/inputs/data_updated_2/attributes/attributes_other.csv")
coordenadas_dir = Path("/home/azureuser/NeuralHydrologyAzure/1_preparing_data/1_uy_basins_data/gauge_data/precip_uy/COORDENADAS.xlsx")

# streamflow stations kml (UY)

In [3]:
area = pd.read_csv(area_file)
area

,gauge_id,gauge_name,country,gauge_lat,gauge_lon,area
0,camels_01013500,"Fish River near Fort Kent, Maine",United States of America,47.237390,-68.582640,2297.683155
1,camels_01022500,"Narraguagus River at Cherryfield, Maine",United States of America,44.607970,-67.935240,619.102595
2,camels_01030500,"Mattawamkeag River near Mattawamkeag, Maine",United States of America,45.500970,-68.305960,3666.943011
3,camels_01031500,"Piscataquis River near Dover-Foxcroft, Maine",United States of America,45.175010,-69.314700,764.824149
4,camels_01047000,"Carrabassett River near North Anson, Maine",United States of America,44.869200,-69.955100,902.895076
...,...,...,...,...,...,...
15971,CAMELS_UY_12,Sarandi del Yi,Uruguay,-33.344139,-55.618417,1381.247863
15972,CAMELS_UY_13,Durazno,Uruguay,-33.360278,-56.524667,8881.479722
15973,CAMELS_UY_14,Paso de los Mellizos,Uruguay,-32.907417,-57.413472,2196.823990
15974,CAMELS_UY_15,Paso de las Piedras (R3),Uruguay,-32.836250,-57.518278,791.650467
15975,CAMELS_UY_16,Bequelo,Uruguay,-33.244444,-57.941222,1141.147308

In [4]:
keep_ids = [
    "CAMELS_UY_2", "CAMELS_UY_3", "CAMELS_UY_5", "CAMELS_UY_6",
    "CAMELS_UY_7", "CAMELS_UY_8", "CAMELS_UY_9", "CAMELS_UY_10",
    "CAMELS_UY_11", "CAMELS_UY_15", "CAMELS_UY_16",
]

df_sub = (
    area[area["gauge_id"].isin(keep_ids)]
    [["gauge_name", "gauge_lat", "gauge_lon"]]
    .reset_index(drop=True)
)

print(df_sub)
assert len(df_sub) == len(keep_ids), "Some IDs weren't found"

                  gauge_name  gauge_lat  gauge_lon
0        Paso de las Piedras -31.530457 -55.584818
1           Paso Manuel Diaz -31.529667 -55.686583
2              Paso Baltasar -31.728558 -55.769773
3          Paso del Borracho -31.876083 -55.471139
4             Paso de Coelho -32.033324 -55.367013
5         Paso de las Toscas -32.158194 -55.023917
6                Paso Aguiar -32.286250 -54.831056
7             Paso Mazangano -32.110028 -54.667500
8              Fraile Muerto -32.519056 -54.529750
9   Paso de las Piedras (R3) -32.836250 -57.518278
10                   Bequelo -33.244444 -57.941222

In [ ]:
kml = simplekml.Kml()
for row in df_sub.itertuples():
    kml.newpoint(name=row.gauge_name, coords=[(row.gauge_lon, row.gauge_lat)])

kml.save("uruguay_gauges.kml")

# precipitation stations kml (UY)

In [6]:
coordenadas = pd.read_excel(coordenadas_dir)
coordenadas

       lat    lon                Estacion Departamento          Tipo     Adm
0   -33.72 -53.55             18 de Julio        Rocha  Convencional  INUMET
1   -34.36 -54.06             19 de Abril        Rocha  Convencional  INUMET
2   -34.41 -56.39            25 de Agosto      Florida  Convencional  INUMET
3   -31.87 -54.16                  Acegua  Cerro Largo  Convencional  INUMET
4   -32.40 -56.18                   Achar   Tacuarembó  Convencional  INUMET
..     ...    ...                     ...          ...           ...     ...
143 -33.12 -57.64            Villa Darwin      Soriano  Convencional  INUMET
144 -34.59 -55.46  Villa Solis de Mataojo    Lavalleja  Convencional  INUMET
145 -33.39 -58.32           Villa Soriano      Soriano  Convencional  INUMET
146 -32.68 -57.64                   Young    Rio Negro  Convencional  INUMET
147 -33.52 -54.94                 Zapican    Lavalleja  Convencional  INUMET

[148 rows x 6 columns]

In [7]:
estaciones = ['Capilla del Sauce', 'Canada Grande', 'Cuchilla Caraguata Norte',
       'Cuchilla del Ombu', 'El Molino', 'Goni', 'Minas de Corrales',
       'Moirones', 'Palmitas', 'Paso de la Cruz_rn', 'Polanco del Yi',
       'Rossell y Rius', 'Tranqueras', 'Vichadero', 'Rivera',
       'Cerro de las Cuentas', 'Cerro Chato']

In [9]:
coordenadas_filtrado = coordenadas.loc[
    coordenadas["Estacion"].isin(estaciones), ["Estacion", "lat", "lon"]
].reset_index(drop=True)

coordenadas_filtrado

                    Estacion    lat    lon
0          Capilla del Sauce -33.46 -55.63
1              Canada Grande -32.51 -57.16
2                Cerro Chato -33.09 -55.14
3       Cerro de las Cuentas -32.61 -54.59
4   Cuchilla Caraguata Norte -32.13 -54.89
5          Cuchilla del Ombu -31.77 -55.69
6                  El Molino -31.71 -56.00
7                       Goni -33.52 -56.41
8          Minas de Corrales -31.57 -55.47
9                   Moirones -31.60 -54.97
10                  Palmitas -33.50 -57.79
11        Paso de la Cruz_rn -32.55 -57.39
12            Polanco del Yi -33.48 -56.15
13                    Rivera -30.89 -55.54
14            Rossell y Rius -33.18 -55.69
15                Tranqueras -31.19 -55.77
16                 Vichadero -31.77 -54.69

In [10]:
kml = simplekml.Kml()
for row in coordenadas_filtrado.itertuples():
    kml.newpoint(name=row.Estacion, coords=[(row.lon, row.lat)])

kml.save("uruguay_precip_gauges.kml")