In [1]:
import geopandas as gpd
import pandas as pd
import matplotlib.pyplot as plt
import xarray as xr
import glob
from pathlib import Path
import matplotlib.dates as mdates
import calendar
import numpy as np
import matplotlib.cm as cm
from adjustText import adjust_text

In [2]:
# -------- Paths --------
gauges_csv = Path("./gauges_in_basins.csv")
UYPRECIP_DIR=Path("./precip_uy")

In [3]:
df = pd.read_csv(gauges_csv)
df

,lat,lon,Estacion,Departamento,Tipo,Adm,geometry,index_right,basin_source
0,-33.46,-55.63,Capilla del Sauce,Florida,Convencional,INUMET,POINT (-55.63 -33.46),0.0,durazno
1,-32.51,-57.16,Cañada Grande,Rio Negro,Convencional,INUMET,POINT (-57.16 -32.51),8.0,paso_de_los_mellizos
2,-32.13,-54.89,Cuchilla Caragauta N,Tacuarembó,Convencional,INUMET,POINT (-54.89 -32.13),4.0,paso_aguiar
3,-31.77,-55.69,Cuchilla del Ombu,Tacuarembó,Convencional,INUMET,POINT (-55.69 -31.77),10.0,paso_del_borracho
4,-31.71,-56.00,El Molino,Tacuarembó,Convencional,INUMET,POINT (-56 -31.71),15.0,tacuarembo
5,-33.52,-56.41,Goñi,Florida,Convencional,INUMET,POINT (-56.41 -33.52),0.0,durazno
6,-31.57,-55.47,Minas de Corrales,Rivera,Convencional,INUMET,POINT (-55.47 -31.57),2.0,paso_de_la_compania
7,-31.57,-55.47,Minas de Corrales,Rivera,Convencional,INUMET,POINT (-55.47 -31.57),10.0,paso_del_borracho
8,-31.60,-54.97,Moirones,Rivera,Convencional,INUMET,POINT (-54.97 -31.6),11.0,picada_de_coelho
9,-33.50,-57.79,Palmitas,Soriano,Convencional,INUMET,POINT (-57.79 -33.5),5.0,bequelo
10,-32.55,-57.39,Paso de la Cruz_RN,Rio Negro,Convencional,INUMET,POINT (-57.39 -32.55),13.0,paso_de_las_piedras_rn
11,-33.48,-56.15,Polanco del Yi,Florida,Convencional,INUMET,POINT (-56.15 -33.48),0.0,durazno
12,-33.18,-55.69,Rossell y Rius,Durazno,Convencional,INUMET,POINT (-55.69 -33.18),0.0,durazno
13,-33.33,-55.62,Sarandi del Yi,Durazno,Convencional,INUMET,POINT (-55.62 -33.33),0.0,durazno
14,-33.72,-56.32,Sarandi Grande,Florida,Convencional,INUMET,POINT (-56.32 -33.72),0.0,durazno
15,-31.19,-55.77,Tranqueras,Rivera,Convencional,INUMET,POINT (-55.77 -31.19),7.0,paso_manuel_diaz
16,-31.19,-55.77,Tranqueras,Rivera,Convencional,INUMET,POINT (-55.77 -31.19),10.0,paso_del_borracho
17,-31.77,-54.69,Vichadero,Rivera,Convencional,INUMET,POINT (-54.69 -31.77),4.0,paso_aguiar
18,-31.77,-54.69,Vichadero,Rivera,Convencional,INUMET,POINT (-54.69 -31.77),12.0,paso_mazangano
19,-30.89,-55.54,Rivera,Rivera,Convencional,INUMET,POINT (-55.54 -30.89),NaN,paso_de_las_piedras
20,-32.61,-54.59,Cerro de las Cuentas,Cerro Largo,Convencional,INUMET,POINT (-54.59 -32.61),NaN,fraile_muerto
21,-33.33,-55.62,Cerro Chato,Durazno,Convencional,INUMET,POINT (-55.62 -33.33),NaN,sarandi_del_yi
22,-31.77,-54.69,Vichadero,Rivera,Convencional,INUMET,POINT (-54.69 -31.77),NaN,paso_de_las_toscas
23,-31.71,-56.00,El Molino,Tacuarembó,Convencional,INUMET,POINT (-56 -31.71),NaN,paso_baltasar

In [4]:
precipitation_file=pd.read_excel(UYPRECIP_DIR / f"{df.loc[0, 'Estacion']} 1981-2024.xlsx", parse_dates=["Fecha"])
precipitation_file

             Estación  Cod. Pluvio      Fecha  [mm] Comentario
0      Cap. del Sauce         2309 1981-01-01   0.0        NaN
1      Cap. del Sauce         2309 1981-01-02  65.0        NaN
2      Cap. del Sauce         2309 1981-01-03   0.0        NaN
3      Cap. del Sauce         2309 1981-01-04   0.0        NaN
4      Cap. del Sauce         2309 1981-01-05  27.0        NaN
...               ...          ...        ...   ...        ...
16054  Cap. del Sauce         2309 2024-12-15   0.0        NaN
16055  Cap. del Sauce         2309 2024-12-16   0.0        NaN
16056  Cap. del Sauce         2309 2024-12-17   0.0        NaN
16057  Cap. del Sauce         2309 2024-12-18   0.0        NaN
16058  Cap. del Sauce         2309 2024-12-19   5.0        NaN

[16059 rows x 5 columns]

In [5]:
start_date = pd.to_datetime("1989-01-01")
end_date = pd.to_datetime("2019-12-31")

In [6]:
precipitation_file=precipitation_file[(precipitation_file["Fecha"] >= start_date) & (precipitation_file["Fecha"] <= end_date)].set_index("Fecha")
precipitation_file.head()

                  Estación  Cod. Pluvio [mm] Comentario
Fecha
1989-01-01  Cap. del Sauce         2309  0.0        NaN
1989-01-02  Cap. del Sauce         2309  0.0        NaN
1989-01-03  Cap. del Sauce         2309  0.0        NaN
1989-01-04  Cap. del Sauce         2309  0.0        NaN
1989-01-05  Cap. del Sauce         2309  0.0        NaN

In [7]:
expected_index = pd.date_range(start=start_date, end=end_date, freq="D")

missing_dates = expected_index.difference(precipitation_file.index)

print(missing_dates)

DatetimeIndex([], dtype='datetime64[ns]', freq='D')

In [8]:
# Amount of missing data

n_missing_flags = (precipitation_file["Comentario"] == "Dato faltante.").sum()

print(n_missing_flags)

59

In [9]:
# Boolean mask for missing
missing = precipitation_file["Comentario"] == "Dato faltante."

# Create groups whenever True/False changes
groups = (missing != missing.shift()).cumsum()

# Compute length of each consecutive missing streak
streak_lengths = missing.groupby(groups).sum()

# Keep only actual missing streaks (length > 0)
streak_lengths = streak_lengths[streak_lengths > 0]

# Count how many streaks of each length exist
streak_distribution = streak_lengths.value_counts().sort_index()

print(streak_distribution)

Comentario
1    53
2     3
Name: count, dtype: int64

In [15]:
for estacion in df["Estacion"].unique():
    print(f"---------{estacion}---------")

    if estacion == "Cañada Grande":
        estacion = "Canada Grande"
    
    if estacion == "Cuchilla Caragauta N":
        estacion = "Cuchilla Caraguata Norte"

    if estacion == "Goñi":
        estacion = "Goni"

    if estacion == "Paso de la Cruz_RN":
        estacion = "Paso de la Cruz_rn"

    if estacion == "Sarandi del Yi":
        continue

    if estacion == "Sarandi Grande":
        continue

    if estacion == "Cuchilla del Ombu":
        precipitation_file=pd.read_excel(UYPRECIP_DIR / f"{estacion} 1982-2024.xlsx", parse_dates=["Fecha"])
    elif estacion == "Tranqueras":
        precipitation_file=pd.read_excel(UYPRECIP_DIR / f"Tranqueras_1982_2024.xlsx", parse_dates=["Fecha"])
    elif estacion == "Vichadero":
        precipitation_file=pd.read_excel(UYPRECIP_DIR / f"Vichadero_1981_2024.xlsx", parse_dates=["Fecha"])
    else:
        precipitation_file=pd.read_excel(UYPRECIP_DIR / f"{estacion} 1981-2024.xlsx", parse_dates=["Fecha"])

    precipitation_file=precipitation_file[(precipitation_file["Fecha"] >= start_date) & (precipitation_file["Fecha"] <= end_date)].set_index("Fecha")

    # Missing dates
    expected_index = pd.date_range(start=start_date, end=end_date, freq="D")
    missing_dates = expected_index.difference(precipitation_file.index)
    print("Missing dates:")
    print(missing_dates)

    # Amount of missing dates
    if estacion == "Tranqueras" or estacion == "Vichadero":
        n_missing_flags = (precipitation_file["ComentarioR3[-]"] == "Dato faltante.").sum()
    else:
        n_missing_flags = (precipitation_file["Comentario"] == "Dato faltante.").sum()
    print("Missing precipitation meassurements:")
    print(n_missing_flags)

    #Distribution of missing streak lengths

    # Boolean mask for missing
    if estacion == "Tranqueras" or estacion == "Vichadero":
        missing = precipitation_file["ComentarioR3[-]"] == "Dato faltante."
    else:
        missing = precipitation_file["Comentario"] == "Dato faltante."

    # Create groups whenever True/False changes
    groups = (missing != missing.shift()).cumsum()

    # Compute length of each consecutive missing streak
    streak_lengths = missing.groupby(groups).sum()

    # Keep only actual missing streaks (length > 0)
    streak_lengths = streak_lengths[streak_lengths > 0]

    # Count how many streaks of each length exist
    streak_distribution = streak_lengths.value_counts().sort_index()

    print("Distribution of missing streak lengths:")
    print(streak_distribution)

---------Capilla del Sauce---------
Missing dates:
DatetimeIndex([], dtype='datetime64[ns]', freq='D')
Missing precipitation meassurements:
59
Distribution of missing streak lengths:
Comentario
1    53
2     3
Name: count, dtype: int64
---------Cañada Grande---------
Missing dates:
DatetimeIndex([], dtype='datetime64[ns]', freq='D')
Missing precipitation meassurements:
134
Distribution of missing streak lengths:
Comentario
1    126
2      4
Name: count, dtype: int64
---------Cuchilla Caragauta N---------
Missing dates:
DatetimeIndex([], dtype='datetime64[ns]', freq='D')
Missing precipitation meassurements:
46
Distribution of missing streak lengths:
Comentario
1    44
2     1
Name: count, dtype: int64
---------Cuchilla del Ombu---------
Missing dates:
DatetimeIndex([], dtype='datetime64[ns]', freq='D')
Missing precipitation meassurements:
71
Distribution of missing streak lengths:
Comentario
1    63
2     4
Name: count, dtype: int64
---------El Molino---------
Missing dates:
DatetimeIndex([], dtype='datetime64[ns]', freq='D')
Missing precipitation meassurements:
20
Distribution of missing streak lengths:
Comentario
1    14
2     3
Name: count, dtype: int64
---------Goñi---------
Missing dates:
DatetimeIndex([], dtype='datetime64[ns]', freq='D')
Missing precipitation meassurements:
89
Distribution of missing streak lengths:
Comentario
1    85
2     2
Name: count, dtype: int64
---------Minas de Corrales---------
Missing dates:
DatetimeIndex([], dtype='datetime64[ns]', freq='D')
Missing precipitation meassurements:
84
Distribution of missing streak lengths:
Comentario
1    82
2     1
Name: count, dtype: int64
---------Moirones---------
Missing dates:
DatetimeIndex([], dtype='datetime64[ns]', freq='D')
Missing precipitation meassurements:
84
Distribution of missing streak lengths:
Comentario
1    80
2     2
Name: count, dtype: int64
---------Palmitas---------
Missing dates:
DatetimeIndex([], dtype='datetime64[ns]', freq='D')
Missing precipitation meassurements:
25
Distribution of missing streak lengths:
Comentario
1    25
Name: count, dtype: int64
---------Paso de la Cruz_RN---------
Missing dates:
DatetimeIndex([], dtype='datetime64[ns]', freq='D')
Missing precipitation meassurements:
91
Distribution of missing streak lengths:
Comentario
1    89
2     1
Name: count, dtype: int64
---------Polanco del Yi---------
Missing dates:
DatetimeIndex([], dtype='datetime64[ns]', freq='D')
Missing precipitation meassurements:
90
Distribution of missing streak lengths:
Comentario
1    84
2     3
Name: count, dtype: int64
---------Rossell y Rius---------
Missing dates:
DatetimeIndex([], dtype='datetime64[ns]', freq='D')
Missing precipitation meassurements:
46
Distribution of missing streak lengths:
Comentario
1    42
2     2
Name: count, dtype: int64
---------Sarandi del Yi---------
---------Sarandi Grande---------
---------Tranqueras---------
Missing dates:
DatetimeIndex([], dtype='datetime64[ns]', freq='D')
Missing precipitation meassurements:
70
Distribution of missing streak lengths:
ComentarioR3[-]
1    62
2     4
Name: count, dtype: int64
---------Vichadero---------
Missing dates:
DatetimeIndex([], dtype='datetime64[ns]', freq='D')
Missing precipitation meassurements:
73
Distribution of missing streak lengths:
ComentarioR3[-]
1    65
2     4
Name: count, dtype: int64
---------Rivera---------
Missing dates:
DatetimeIndex([], dtype='datetime64[ns]', freq='D')
Missing precipitation meassurements:
0
Distribution of missing streak lengths:
Series([], Name: count, dtype: int64)
---------Cerro de las Cuentas---------
Missing dates:
DatetimeIndex([], dtype='datetime64[ns]', freq='D')
Missing precipitation meassurements:
148
Distribution of missing streak lengths:
Comentario
1    136
2      6
Name: count, dtype: int64
---------Cerro Chato---------
Missing dates:
DatetimeIndex([], dtype='datetime64[ns]', freq='D')
Missing precipitation meassurements:
7
Distribution of missing streak lengths:
Comentario
1    7
Name: count, dtype: int64

In [ ]:
# ver todos los archivos para ver que los comentarios sean iguales
# que hizo horudour para mas de un dia consecutivo